[package]
name = "fhe_voting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fhe = "0.1.0-beta.7"
fhe-traits = "0.1.0-beta.7"
